### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by uniunieh** [snuwebprogramming-22-1/snu-chat#10]
처음에 시작할 때 
npm start하면 팝업으로 

App.js의 1행에 오류가 있다면서,
code: 800A03EA, 컴파일 오류 뜨는데 왜 그런 건가요? 

json 파일에는 아래와 같이 적어넣었습니다. ㅏ
![image](https://user-images.githubusercontent.com/106761901/171676734-e1ffa6c1-eba6-4665-a4e6-3d98b45aaead.png)

참고로 App.js 파일은 아래와 같습니다. 
![image](https://user-images.githubusercontent.com/106761901/171676876-78447901-b6a2-492f-bc80-60e51bd54002.png)

**Comment by realcom** [comment]
오류 메시지 풀로 작성해주세요

**Comment by uniunieh** [comment]
**Script:** (제가 지금 밖이라 이 부분 확인을 못 하는데 마지막은 App.js로 되어 있었던 것 같아요)
**Line:** 1
**Char:**  1
**Error:** Syntax error
**Code:** 800A03EA
**Source:** Microsoft JScript compilation error


예시 이미지

![image](https://user-images.githubusercontent.com/106761901/171787375-6508d1a1-d758-48ec-b97f-9746672c3e86.png)

**Comment by uniunieh** [comment]
해결했습니다!
